# Generated by Django 3.1.2 on 2020-10-25 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='open_in_tab',
            new_name='open_in_new_tab',
        ),
    ]
