# Generated by Django 3.1.2 on 2020-10-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocailMediaSettings',
            new_name='SocialMediaSettings',
        ),
    ]
